### ISSUE TITLE
Consider supporting multiple configuration files

### ISSUE THREAD

**Issue by andrewla** [ericfreese/rat#17]
To make it easier to enable and disable different configurations, consider grabbing all files according to some pattern.  I would suggest either

```
~/.config/rat/git.ratrc
~/.config/rat/files.ratrc
```

Or, more verbosely,

```
~/.config/rat/git-rat/git.ratrc
~/.config/rat/files-rat/files.ratrc
```

The latter has the advantage of being able to `git clone` a project (like https://github.com/ericfreese/files-rat) and maintain it by doing occasional `git pull`s to update.  This idea sort-of stolen from how most vim plugin managers work, although direct git integration might not be desirable.

**Comment by ericfreese** [comment]
This is a great idea. I'll look into this.

**Comment by ericfreese** [comment]
Thanks to @jordansgrant, we now support sourcing additional rat config files via `source`. It will take either a file name or path so it supports your idea for clone-able rat config repos. In your ratrc, you would add something like:

```
source git-rat/git.ratrc
source files-rat/files.ratrc
```

While it's not automatic (doesn't automatically source everything in the folder), I think it satisfies the requirements enough to close this issue.
