### ISSUE TITLE
example of a regex annotator

### ISSUE THREAD

**Issue by atomotic** [ericfreese/rat#27]
could you provide an example of regex annotator?
 
i would like to parse something like this:
`{"offset": "470", ...BLAHBLAH...}`

i tried: `annotate regex index -- {\"offset\": "(\d*)"`
i would expect `%(index) = 470`

thanks

**Comment by ericfreese** [comment]
So I think what you need here is to use the first capture group `(\d*)` as the value of the annotation. I don't think this is possible using the built-in regex annotator, but you can use [the external one](https://github.com/ericfreese/rat/blob/master/annotators/regex). See the docs on `external` annotators in [the readme](https://github.com/ericfreese/rat#annotator-definitions).

You'll then want to pass the `--value-match <n>` option to specify which capture group you want to use for the value of the annotation.

I use a similar approach in my config here: https://github.com/ericfreese/Dotfiles/blob/arch/.config/rat/.ratrc#L101

**Comment by atomotic** [comment]
thanks! now i understand better how external annotators works.
for my need actually i found another solution
https://gist.github.com/atomotic/c6d6c9f59bdd4fa22d166690a4cc5dc6

thanks for this tool, is great
