### ISSUE TITLE
Keystrokes not registering

### ISSUE THREAD

**Issue by benjamin-thomas** [ericfreese/rat#42]
Hello,

I'd like to try your tool, but somehow I can't figure out if I'm doing something wrong.

---

```bash
$ rat --version
0.0.2 
```

---

### Config file (tried ~/.ratrc and ~/.config/rat)

```bash
bindkey C-r reload
bindkey j   cursor-down
bindkey k   cursor-up
bindkey f1   cursor-down

mode files
  # Find all files (not directories) in the current directory and
  # annotate with the class "file".
  annotate match file -- ls -a1p | grep -v /

  # When the cursor is on a line with an annotation of class "file" and
  # the `enter` key is pressed, run `cat` with the value of the
  # annotation (the filename) and display the output in a new pager with
  # mode "preview".
  bindkey enter file preview -- >cat $file

  # When the cursor is on a line with an annotation of class "file" and
  # the `e` key is pressed, open the selected file in vim.
  bindkey e     file         -- !vim $file

  # When the cursor is on a line with an annotation of class "file" and
  # Shift + `x` is pressed, delete the file if the user confirms it.
  bindkey S-x   file         -- ?!rm $file
end
```

---

### Executed command

```bash
rat --mode files --cmd 'ls -al'
```

---

I can see the output with the red cursor just fine, but no key press registers.

I'm using the i3 window manager, on ubuntu 16.04. I'm using an unusual dvorak style layout, but I can't see how that would be an issue.

I tried using 2 different terminals: `gnome-terminal` and `urxvt`, inside and outside tmux.

---

Since your rely on the `termbox-go`, I tested the following demo, which works.

```bash
cd $GOPATH/src/github.com/nsf/termbox-go/_demos
go run keyboard.go
```

Any ideas?

**Comment by ericfreese** [comment]
I apologize the readme is a bit unclear on this, but It's actually looking for the config file to be located at `~/.config/rat/ratrc`.

**Comment by ericfreese** [comment]
Also take a look at my personal rat config dir for more examples: https://github.com/ericfreese/Dotfiles/tree/arch/.config/rat

**Comment by benjamin-thomas** [comment]
It was a dumb file path issue indeed.

Thanks for the feedback !
