### ISSUE TITLE
No key commands working

### ISSUE THREAD

**Issue by tekknolagi** [ericfreese/rat#44]
I installed this tool with `go get`, but none of the key commands appear to be working. I am running the `ls` example from the README. I am running Ubuntu 18.04, go 1.10.4.

**Comment by ericfreese** [comment]
Have you added a config file with keybindings?

https://github.com/ericfreese/rat#keybindings

make sure the config file is at `~/.config/rat/ratrc`

**Comment by tekknolagi** [comment]
I have added the suggested keybindings from the README.

**Comment by tekknolagi** [comment]
Oh, shoot. I misunderstood the README. I thought it suggested the file be called `~/.config/rat`.
